sudo: false
language: php
php:
  - 5.6
  - 7
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
  - $HOME/.composer/cache

script:
  - ./web/vendor/bin/phpunit --configuration tests/phpunit.xml

before_script:
  - composer install -d web/

